[package]
name = "adv-rs"
version = "0.1.0"
authors = ["Marc Noirot <marc.noirot@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
chrono = "0.4"
regex = "1"

[build-dependencies]
chrono = "0.4"
